In [29]:
import pandas as pd
import numpy as np

In [30]:
listOfOrders = pd.read_excel("../data/raw/List_of_Orders.xlsx")
orderDetails = pd.read_excel("../data/raw/Order_Details.xlsx")
salesTarget = pd.read_excel("../data/raw/Sales_target.xlsx")

In [31]:
listOfOrders.head()

  Order ID  Order Date CustomerName           State      City
0  B-26101  01-04-2019      Jesslyn     Maharashtra      Pune
1  B-26102  02-04-2019        Pooja   Uttar Pradesh   Lucknow
2  B-26103  03-04-2019        Ayush          Punjab  Amritsar
3  B-26104  03-04-2019      Sanjana     Maharashtra    Mumbai
4  B-26105  03-04-2019      Manjiri  Madhya Pradesh    Indore

In [32]:
listOfOrders.isnull().sum()

Order ID        0
Order Date      0
CustomerName    0
State           0
City            0
dtype: int64

In [33]:
listOfOrders.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      500 non-null    str
 1   Order Date    500 non-null    str
 2   CustomerName  500 non-null    str
 3   State         500 non-null    str
 4   City          500 non-null    str
dtypes: str(5)
memory usage: 19.7 KB

In [34]:
listOfOrders.describe()

       Order ID  Order Date CustomerName           State    City
count       500         500          500             500     500
unique      500         173          242              19      24
top     B-26101  08-04-2019     Sonakshi  Madhya Pradesh  Mumbai
freq          1           5            8             107      76

In [35]:
orderDetails.head()

  Order ID  Amount  Profit  Quantity     Category Sub-Category
0  B-26101       7      -3         2     Clothing        Skirt
1  B-26102      30      13         1     Clothing      T-shirt
2  B-26103    1854     433         5    Furniture    Bookcases
3  B-26104    1319     567         5  Electronics     Printers
4  B-26104     105      20         2     Clothing        Stole

In [36]:
orderDetails.isnull().sum()

Order ID        0
Amount          0
Profit          0
Quantity        0
Category        0
Sub-Category    0
dtype: int64

In [37]:
orderDetails.describe()

            Amount       Profit     Quantity
count  1522.000000  1522.000000  1522.000000
mean    277.499343     5.842313     3.777267
std     476.095247   183.264359     2.149797
min       6.000000 -1981.000000     1.000000
25%      44.000000   -10.000000     2.000000
50%     113.000000     8.000000     3.000000
75%     299.000000    37.000000     5.000000
max    5729.000000  1151.000000    14.000000

In [38]:
salesTarget.head()

   Month of Order Date   Category   Target
0  2026-04-19 00:00:00  Furniture  11900.0
1  2026-05-19 00:00:00  Furniture  12000.0
2  2026-06-19 00:00:00  Furniture  12100.0
3  2026-07-19 00:00:00  Furniture  12300.0
4  2026-08-19 00:00:00  Furniture  12400.0

In [39]:
salesTarget.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Month of Order Date  19 non-null     object
 1   Category             18 non-null     str
 2   Target               18 non-null     float64
dtypes: float64(1), object(1), str(1)
memory usage: 612.0+ bytes

In [40]:
salesTarget.isnull().sum()

Month of Order Date    1
Category               2
Target                 2
dtype: int64

In [41]:
salesTarget.describe()

             Target
count     18.000000
mean   14733.333333
std     1847.733110
min    11900.000000
25%    12425.000000
50%    16000.000000
75%    16000.000000
max    16000.000000

In [42]:
salesTarget.duplicated().sum()

np.int64(0)

In [43]:
listOfOrders.duplicated().sum()

np.int64(0)

In [44]:
orderDetails.duplicated().sum()

np.int64(3)

In [45]:
orderDetails.shape

(1522, 6)

In [46]:
listOfOrders.shape

(500, 5)

In [47]:
salesTarget.shape

(20, 3)

In [48]:
salesTarget.dtypes

Month of Order Date     object
Category                   str
Target                 float64
dtype: object

In [49]:
listOfOrders.dtypes

Order ID        str
Order Date      str
CustomerName    str
State           str
City            str
dtype: object

In [50]:
orderDetails.dtypes

Order ID          str
Amount          int64
Profit          int64
Quantity        int64
Category          str
Sub-Category      str
dtype: object

In [51]:
missing_orders = (
    orderDetails[
        ~orderDetails["Order ID"].isin(listOfOrders["Order ID"])
    ]
)

print("Missing Order IDs:", len(missing_orders))
missing_orders.head()

Missing Order IDs: 0

Empty DataFrame
Columns: [Order ID, Amount, Profit, Quantity, Category, Sub-Category]
Index: []

In [52]:
listOfOrders["Order Date"] = pd.to_datetime(
    listOfOrders["Order Date"],
    dayfirst=True
)

In [53]:
orderDetails["Category"].value_counts()

Category
Clothing       970
Electronics    298
Furniture      254
Name: count, dtype: int64

In [54]:
orderDetails["Sub-Category"].value_counts()

Sub-Category
Stole               209
Hankerchief         205
Saree               192
Phones               96
Chairs               89
Electronic Games     84
T-shirt              80
Shirt                79
Bookcases            77
Skirt                69
Furnishings          69
Accessories          67
Leggings             55
Printers             51
Kurti                46
Trousers             35
Tables               19
Name: count, dtype: int64

In [55]:
print((orderDetails["Amount"] <= 0).sum())
print((orderDetails["Quantity"] <= 0).sum())
print((orderDetails["Profit"].isnull()).sum())

0
0
0